import { z } from "zod";
import { isValidPhoneNumber } from "~/lib/whatsapp";

/**
 * Validation schemas for the vehicle creation wizard
 * These match the backend validation in user-vehicle.ts
 */

// Profile step validation
export const profileSchema = z.object({
  firstName: z.string().min(1, "First name is required"),
  lastName: z.string().min(1, "Last name is required"),
  phone: z
    .string()
    .min(1, "Phone number is required")
    .refine(
      (val) => isValidPhoneNumber(val),
      "Please enter a valid phone number"
    ),
  street: z.string().min(1, "Street address is required"),
  city: z.string().min(1, "City is required"),
  county: z.string().min(1, "County is required"),
  postcode: z
    .string()
    .min(1, "Postcode is required")
    .refine(
      (val) => {
        // Remove spaces and convert to uppercase for validation
        const normalized = val.replace(/\s+/g, "").toUpperCase();
        // UK postcode format: 1-2 letters, 1-2 digits, optional letter, digit, 2 letters
        // Examples: SW1A1AA, M11AE, B338TH, CR26XH
        return /^[A-Z]{1,2}\d{1,2}[A-Z]?\d[A-Z]{2}$/.test(normalized);
      },
      "Please enter a valid UK postcode (e.g., SW1A 1AA)"
    ),
  countryId: z.string().min(1, "Country is required"),
  latitude: z.number().optional(),
  longitude: z.number().optional(),
});

export type ProfileFormData = z.infer<typeof profileSchema>;

// Basic info step validation
export const basicInfoSchema = z.object({
  makeId: z.string().min(1, "Make is required"),
  modelId: z.string().min(1, "Model is required"),
  year: z.string()
    .min(1, "Year is required")
    .refine(
      (val) => /^\d{4}$/.test(val),
      "Year must be exactly 4 digits"
    )
    .refine(
      (val) => {
        const year = parseInt(val, 10);
        const currentYear = new Date().getFullYear();
        return year >= 1900 && year <= currentYear;
      },
      (val) => ({
        message: `Year must be between 1900 and ${new Date().getFullYear()}`,
      })
    ),
  registration: z.string()
    .min(1, "Registration is required")
    .refine(
      (val) => /^[A-Z0-9]+$/.test(val),
      "Registration must contain only uppercase letters and numbers"
    ),
  price: z
    .string()
    .min(1, "Agreed value is required")
    .refine(
      (val) => !isNaN(Number(val)) && Number(val) > 0,
      "Agreed value must be a valid number greater than 0"
    ),
});

export type BasicInfoFormData = z.infer<typeof basicInfoSchema>;

// Type for the transformed data (after converting price to number)
export type BasicInfoSubmitData = Omit<BasicInfoFormData, 'price'> & {
  price: number;
};

// Technical details step validation
export const technicalDetailsSchema = z.object({
  engineCapacity: z
    .string()
    .min(1, "Engine capacity is required")
    .refine(
      (val) => !isNaN(Number(val)) && Number(val) >= 1,
      "Engine capacity must be a valid number greater than 0"
    ),
  numberOfSeats: z.number().min(1).max(10, "Number of seats must be between 1 and 10"),
  steeringId: z.string().min(1, "Steering type is required"),
  gearbox: z.string().min(1, "Gearbox is required"),
  exteriorColour: z.string().min(1, "Exterior colour is required"),
  interiorColour: z.string().min(1, "Interior colour is required"),
  condition: z.string().min(1, "Condition is required"),
  isRoadLegal: z.boolean(),
});

export type TechnicalDetailsFormData = z.infer<typeof technicalDetailsSchema>;

// Type for the transformed data (after converting engineCapacity to number)
export type TechnicalDetailsSubmitData = Omit<TechnicalDetailsFormData, 'engineCapacity'> & {
  engineCapacity: number;
};

// Vehicle details step validation (Description, Collections, Pricing)
// Note: Name is auto-generated by backend from year, make, model
export const vehicleDetailsSchema = z.object({
  name: z.string().optional(), // Optional - backend will auto-generate if not provided
  description: z.string().optional(),
  collectionIds: z.array(z.string()).optional(),
  hourlyRate: z
    .string()
    .min(1, "Hourly rate is required")
    .refine(
      (val) => !isNaN(Number(val)) && Number(val) >= 0,
      "Hourly rate must be a valid number"
    ),
  dailyRate: z
    .string()
    .min(1, "Daily rate is required")
    .refine(
      (val) => !isNaN(Number(val)) && Number(val) >= 0,
      "Daily rate must be a valid number"
    ),
});

export type VehicleDetailsFormData = z.infer<typeof vehicleDetailsSchema>;

// Type for the submit data (after converting rates to numbers)
export type VehicleDetailsSubmitData = Omit<VehicleDetailsFormData, 'hourlyRate' | 'dailyRate'> & {
  hourlyRate: number;
  dailyRate: number;
};

// Combined schema for full vehicle creation
export const fullVehicleSchema = basicInfoSchema
  .merge(technicalDetailsSchema)
  .merge(vehicleDetailsSchema);

export type FullVehicleFormData = z.infer<typeof fullVehicleSchema>;

// Helper function to check if profile is complete
export function isProfileComplete(user: {
  firstName?: string | null;
  lastName?: string | null;
  phone?: string | null;
  city?: string | null;
  postcode?: string | null;
}): boolean {
  return Boolean(
    user.firstName && 
    user.lastName && 
    user.phone && 
    user.city && 
    user.postcode
  );
}

