"use client";

import { useEffect, useMemo, useState, useRef } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { Check, Sparkles, Info } from "lucide-react";
import { toast } from "sonner";
import {
  Form,
  FormControl,
  FormDescription,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "~/components/ui/form";
import { Input } from "~/components/ui/input";
import { Label } from "~/components/ui/label";
import { Textarea } from "~/components/ui/textarea";
import { Alert, AlertDescription } from "~/components/ui/alert";
import { api } from "~/trpc/react";
import { vehicleDetailsSchema, type VehicleDetailsFormData, type VehicleDetailsSubmitData } from "./validation";
import type { CollectionItem } from "./types";
import { calculateDefaultPricing, formatPricingRate } from "~/lib/pricing";

interface VehicleDetailsStepProps {
  onComplete: (data: VehicleDetailsSubmitData) => void;
  defaultValues?: Partial<VehicleDetailsSubmitData>;
  onValidationChange?: (isValid: boolean) => void;
  autoGeneratedName?: string; // Name generated from make, model, year
  vehicleData?: {
    makeId: string;
    modelId: string;
    year: string;
    engineCapacity: number;
    numberOfSeats: number;
    steeringId: string;
    gearbox: string;
    exteriorColour: string;
    interiorColour: string;
    isRoadLegal: boolean;
    price: number; // Agreed value for calculating default pricing
  };
}

/**
 * Vehicle Details Step Component
 * 
 * Collects final vehicle details:
 * - Description (optional)
 * - Collections/Tags (optional)
 * 
 * Note: Vehicle name is auto-generated by the backend from year, make, and model.
 * Vehicle is created after this step is completed.
 */
export function VehicleDetailsStep({
  onComplete,
  defaultValues,
  onValidationChange,
  autoGeneratedName,
  vehicleData,
}: VehicleDetailsStepProps) {
  const [isGenerating, setIsGenerating] = useState(false);
  
  // Track if AI generation has already occurred to prevent regeneration on remount
  // Initialize based on whether defaultValues already has a description (from saved data)
  const hasGeneratedRef = useRef(!!(defaultValues?.description && defaultValues.description.trim().length > 0));

  // Calculate default pricing based on vehicle price
  const defaultPricing = useMemo(() => {
    if (vehicleData?.price) {
      return calculateDefaultPricing(vehicleData.price);
    }
    return null;
  }, [vehicleData?.price]);

  // Fetch filter options for collections
  const { data: filterOptions, isLoading: isLoadingFilters } =
    api.userVehicle.getFilterOptions.useQuery();

  // AI generation mutation
  const generateContentMutation = api.userVehicle.generateVehicleContent.useMutation();

  // Store initial description to check if it was provided
  const initialDescription = defaultValues?.description ?? "";
  const hasInitialDescription = !!(initialDescription && initialDescription.trim().length > 0);
  
  // If we have an initial description, mark as generated immediately
  if (hasInitialDescription && !hasGeneratedRef.current) {
    hasGeneratedRef.current = true;
  }

  const form = useForm<VehicleDetailsFormData>({
    resolver: zodResolver(vehicleDetailsSchema),
    defaultValues: {
      name: "", // Will be auto-generated by backend
      description: initialDescription,
      collectionIds: defaultValues?.collectionIds ?? [],
      hourlyRate: defaultValues?.hourlyRate?.toString() ?? defaultPricing?.hourlyRate.toString() ?? "",
      dailyRate: defaultValues?.dailyRate?.toString() ?? defaultPricing?.dailyRate.toString() ?? "",
    },
  });

  // Sync form with defaultValues when they change (e.g., when navigating back with saved data)
  useEffect(() => {
    if (defaultValues?.description !== undefined) {
      const currentDescription = form.getValues("description");
      // Only update if the form value is empty or different from defaultValues
      if (!currentDescription || currentDescription !== defaultValues.description) {
        form.setValue("description", defaultValues.description, { shouldValidate: true });
      }
      // If defaultValues has a description, mark as already generated to prevent regeneration
      if (defaultValues.description && defaultValues.description.trim().length > 0) {
        hasGeneratedRef.current = true;
      }
    }
    if (defaultValues?.collectionIds !== undefined) {
      form.setValue("collectionIds", defaultValues.collectionIds, { shouldValidate: true });
    }
  }, [defaultValues?.description, defaultValues?.collectionIds, form]);

  // Set default pricing when calculated
  useEffect(() => {
    if (defaultPricing && !defaultValues?.hourlyRate && !defaultValues?.dailyRate) {
      form.setValue("hourlyRate", defaultPricing.hourlyRate.toString(), { shouldValidate: true });
      form.setValue("dailyRate", defaultPricing.dailyRate.toString(), { shouldValidate: true });
    }
  }, [defaultPricing, defaultValues, form]);

  // Track current vehicle IDs to detect when vehicle changes
  const previousVehicleIdsRef = useRef<{ makeId?: string; modelId?: string }>({});

  // Generate AI content on mount if vehicle data is provided
  useEffect(() => {
    // CRITICAL: Check ref FIRST - if already generated, never generate again
    if (hasGeneratedRef.current) {
      return;
    }
    
    // CRITICAL: Check if we already have a description - this must be checked SECOND
    // Check multiple sources: initialDescription, defaultValues, and form state
    const hasDescriptionInInitial = hasInitialDescription;
    const hasDescriptionInDefaultValues = !!(defaultValues?.description && defaultValues.description.trim().length > 0);
    const currentFormDescription = form.getValues("description");
    const hasDescriptionInForm = !!(currentFormDescription && currentFormDescription.trim().length > 0);
    const hasExistingDescription = hasDescriptionInInitial || hasDescriptionInDefaultValues || hasDescriptionInForm;
    
    // If we have a description anywhere, mark as generated and don't generate
    if (hasExistingDescription) {
      hasGeneratedRef.current = true;
      // Ensure form is synced if needed
      if (hasDescriptionInDefaultValues && !hasDescriptionInForm) {
        form.setValue("description", defaultValues.description!, { shouldValidate: true });
      }
      // Early return - do NOT generate if description exists
      return;
    }
    
    // Reset generation flag if vehicle IDs have changed (user changed make/model)
    const currentMakeId = vehicleData?.makeId;
    const currentModelId = vehicleData?.modelId;
    const previousIds = previousVehicleIdsRef.current;
    
    if (currentMakeId !== previousIds.makeId || currentModelId !== previousIds.modelId) {
      // Vehicle changed, reset generation flag to allow new generation
      hasGeneratedRef.current = false;
      previousVehicleIdsRef.current = { makeId: currentMakeId, modelId: currentModelId };
    }
    
    // Only generate if:
    // 1. We have vehicle data
    // 2. No description exists yet (neither in defaultValues nor form)
    // 3. We haven't already generated for this vehicle (tracked by ref)
    if (vehicleData && !hasGeneratedRef.current) {
      const generateContent = async () => {
        setIsGenerating(true);
        try {
          const generated = await generateContentMutation.mutateAsync(vehicleData);
          
          // Set the generated description (name is handled by backend)
          form.setValue("description", generated.description, { shouldValidate: true });
          
          // Mark as generated to prevent regeneration on remount
          hasGeneratedRef.current = true;
          
          toast.success("Vehicle description generated with AI!");
        } catch (error) {
          console.error("Failed to generate content:", error);
          toast.error("Failed to generate AI content. You can add a description manually.");
        } finally {
          setIsGenerating(false);
        }
      };

      void generateContent();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [vehicleData?.makeId, vehicleData?.modelId, defaultValues?.description]); // Include defaultValues?.description to re-check when it changes

  // Watch form validity and notify parent
  useEffect(() => {
    const subscription = form.watch(() => {
      const isValid = form.formState.isValid;
      onValidationChange?.(isValid);
    });
    return () => subscription.unsubscribe();
  }, [form, onValidationChange]);

  // Expose submit function to parent via ref (for Next button)
  useEffect(() => {
    (window as any).__currentStepSubmit = () => {
      form.handleSubmit((data) => {
        // Convert pricing rates from strings to numbers
        const submitData: VehicleDetailsSubmitData = {
          ...data,
          hourlyRate: data.hourlyRate ? Number(data.hourlyRate) : 0,
          dailyRate: data.dailyRate ? Number(data.dailyRate) : 0,
        };
        onComplete(submitData); 
      })();
    };
    return () => {
      delete (window as any).__currentStepSubmit;
    };
  }, [form, onComplete]);

  const watchDescription = form.watch("description");
  const descriptionLength = watchDescription?.length ?? 0;

  // Save form data to sessionStorage whenever description changes (for auto-save on back navigation)
  useEffect(() => {
    const currentDescription = form.getValues("description");
    const currentCollectionIds = form.getValues("collectionIds") ?? [];
    const currentHourlyRate = form.getValues("hourlyRate");
    const currentDailyRate = form.getValues("dailyRate");
    
    // Only save if we have a non-empty description (don't overwrite saved data with empty)
    // This prevents overwriting saved descriptions when component remounts with empty form
    if (currentDescription && currentDescription.trim().length > 0) {
      try {
        // Merge with existing data to preserve other fields
        const existingDataStr = sessionStorage.getItem("vehicle_wizard_vehicle_details");
        const existingData = existingDataStr ? JSON.parse(existingDataStr) : {};
        
        const dataToSave = {
          ...existingData, // Preserve existing data
          description: currentDescription, // Update with current description
          collectionIds: currentCollectionIds.length > 0 ? currentCollectionIds : (existingData.collectionIds || []),
          hourlyRate: currentHourlyRate ? Number(currentHourlyRate) : (existingData.hourlyRate || undefined),
          dailyRate: currentDailyRate ? Number(currentDailyRate) : (existingData.dailyRate || undefined),
        };
        sessionStorage.setItem("vehicle_wizard_vehicle_details", JSON.stringify(dataToSave));
      } catch (error) {
        console.error("Failed to save vehicle details to sessionStorage:", error);
      }
    }
  }, [watchDescription, form]);

  // Convert collections to options
  const collectionOptions: CollectionItem[] = useMemo(() => {
    const collections = filterOptions?.collections as CollectionItem[] | undefined;
    return collections ?? [];
  }, [filterOptions?.collections]);

  return (
    <div className="space-y-6">
      {/* Loading overlay */}
      {isGenerating && (
        <div className="fixed inset-0 bg-background/80 backdrop-blur-sm z-50 flex items-center justify-center">
          <div className="bg-card border rounded-lg p-8 shadow-lg max-w-md mx-4">
            <div className="flex flex-col items-center gap-4">
              <div className="relative">
                <div className="animate-spin rounded-full h-16 w-16 border-b-2 border-primary"></div>
                <Sparkles className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 h-8 w-8 text-primary" />
              </div>
              <div className="text-center">
                <h3 className="text-lg font-semibold">Generating with AI</h3>
                <p className="text-sm text-muted-foreground mt-1">
                  Creating a compelling description for your vehicle...
                </p>
              </div>
            </div>
          </div>
        </div>
      )}

      <div className="w-full flex flex-col gap-3 items-center text-center mb-6">
        <h2 className="text-[32px] md:text-[40px] font-normal leading-[0.95] uppercase text-black tracking-[-0.4px]">
          Vehicle Listing
        </h2>
        <p className="text-[18px] md:text-[22px] font-normal leading-[1.3] text-black tracking-[-0.22px]">
          Name, description, and collections
        </p>
      </div>

      <Form {...form}>
        <form className="space-y-6">
          {/* Description */}
          <FormField
            control={form.control}
            name="description"
            render={({ field }) => (
              <FormItem>
                <FormLabel className="text-sm md:text-base">Description</FormLabel>
                <FormControl>
                  <Textarea
                    placeholder="Tell us about your vehicle's history, features, modifications, etc."
                    className="min-h-[120px] md:min-h-[150px] resize-none text-base md:text-sm"
                    disabled={isGenerating}
                    {...field}
                    value={field.value ?? ""}
                  />
                </FormControl>
                <div className="flex justify-between items-center min-h-[20px]">
                  <FormDescription className="text-xs md:text-sm">
                    Optional but recommended for better visibility
                  </FormDescription>
                  <span className="text-xs text-muted-foreground">{descriptionLength} / 2000</span>
                </div>
                <FormMessage />
              </FormItem>
            )}
          />

          {/* Collections & Tags */}
          <FormField
            control={form.control}
            name="collectionIds"
            render={({ field }) => (
              <FormItem>
                <FormLabel className="text-sm md:text-base">Collections & Tags</FormLabel>
                <FormControl>
                  <div className="flex flex-wrap gap-2">
                    {collectionOptions.length > 0 ? (
                      collectionOptions.map((collection) => {
                        const isSelected = (field.value ?? []).includes(collection.id);
                        return (
                          <button
                            key={collection.id}
                            type="button"
                            onClick={() => {
                              const currentIds = field.value ?? [];
                              if (isSelected) {
                                // Remove if already selected
                                field.onChange(currentIds.filter((id: string) => id !== collection.id));
                              } else {
                                // Add if not selected
                                field.onChange([...currentIds, collection.id]);
                              }
                            }}
                            disabled={isLoadingFilters || isGenerating}
                            className={`
                              px-3 md:px-4 py-2 rounded-md border-2 transition-all text-sm md:text-base
                              ${isSelected 
                                ? 'border-primary bg-primary text-primary-foreground shadow-sm' 
                                : 'border-input bg-background hover:bg-accent hover:text-accent-foreground'
                              }
                            `}
                            style={
                              isSelected && collection.color
                                ? {
                                    backgroundColor: collection.color,
                                    borderColor: collection.color,
                                    color: '#ffffff',
                                  }
                                : {}
                            }
                          >
                            <div className="flex items-center gap-2">
                              {collection.color && !isSelected && (
                                <div
                                  className="w-3 h-3 rounded-full"
                                  style={{ backgroundColor: collection.color }}
                                />
                              )}
                              <span>{collection.name}</span>
                            </div>
                          </button>
                        );
                      })
                    ) : (
                      <p className="text-sm text-muted-foreground">No collections available</p>
                    )}
                  </div>
                </FormControl>
                <FormDescription className="min-h-[20px] text-xs md:text-sm">
                  Select one or more collections to help users find your vehicle
                </FormDescription>
                <FormMessage />
              </FormItem>
            )}
          />

          {/* Hire Pricing */}
          {defaultPricing && (
            <div className="space-y-4 border-t pt-6">
              <div>
                <h3 className="text-base md:text-lg font-semibold">Hire Pricing</h3>
                <p className="text-xs md:text-sm text-muted-foreground mt-1">
                  Set your hourly and daily hire rates
                </p>
              </div>

              {/* Pricing Tier Info */}
              <Alert>
                <Info className="h-4 w-4" />
                <AlertDescription className="text-xs md:text-sm">
                  Based on the information you provided, we suggest £{defaultPricing.hourlyRate}/hour and £{defaultPricing.dailyRate}/day. You can adjust these rates as needed.
                </AlertDescription>
              </Alert>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {/* Hourly Rate */}
                <FormField
                  control={form.control}
                  name="hourlyRate"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel className="text-sm md:text-base">Hourly Rate (£)</FormLabel>
                      <FormControl>
                        <div className="relative">
                          <span className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground">£</span>
                          <Input
                            type="number"
                            placeholder={defaultPricing?.hourlyRate.toString() ?? "60"}
                            className="pl-7 text-base md:text-sm"
                            disabled={isGenerating}
                            {...field}
                            value={field.value ?? ""}
                          />
                        </div>
                      </FormControl>
                      <FormDescription className="text-xs md:text-sm">
                        Per hour rate in GBP
                      </FormDescription>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                {/* Daily Rate */}
                <FormField
                  control={form.control}
                  name="dailyRate"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel className="text-sm md:text-base">Daily Rate (£)</FormLabel>
                      <FormControl>
                        <div className="relative">
                          <span className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground">£</span>
                          <Input
                            type="number"
                            placeholder={defaultPricing?.dailyRate.toString() ?? "300"}
                            className="pl-7 text-base md:text-sm"
                            disabled={isGenerating}
                            {...field}
                            value={field.value ?? ""}
                          />
                        </div>
                      </FormControl>
                      <FormDescription className="text-xs md:text-sm">
                        Up to 12 hours in GBP
                      </FormDescription>
                      <FormMessage />
                    </FormItem>
                  )}
                />
              </div>
            </div>
          )}
        </form>
      </Form>
    </div>
  );
}

