"use client";

import { useEffect, useMemo, useState } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { Check, Sparkles } from "lucide-react";
import { toast } from "sonner";
import {
  Form,
  FormControl,
  FormDescription,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "~/components/ui/form";
import { Input } from "~/components/ui/input";
import { Label } from "~/components/ui/label";
import { Textarea } from "~/components/ui/textarea";
import { api } from "~/trpc/react";
import { vehicleDetailsSchema, type VehicleDetailsFormData, type VehicleDetailsSubmitData } from "./validation";
import type { CollectionItem } from "./types";

interface VehicleDetailsStepProps {
  onComplete: (data: VehicleDetailsSubmitData) => void;
  defaultValues?: Partial<VehicleDetailsSubmitData>;
  onValidationChange?: (isValid: boolean) => void;
  autoGeneratedName?: string; // Name generated from make, model, year
  vehicleData?: {
    makeId: string;
    modelId: string;
    year: string;
    engineCapacity: number;
    numberOfSeats: number;
    steeringId: string;
    gearbox: string;
    exteriorColour: string;
    interiorColour: string;
    isRoadLegal: boolean;
  };
}

/**
 * Vehicle Details Step Component
 * 
 * Collects final vehicle details:
 * - Description (optional)
 * - Collections/Tags (optional)
 * 
 * Note: Vehicle name is auto-generated by the backend from year, make, and model.
 * Vehicle is created after this step is completed.
 */
export function VehicleDetailsStep({
  onComplete,
  defaultValues,
  onValidationChange,
  autoGeneratedName,
  vehicleData,
}: VehicleDetailsStepProps) {
  const [isGenerating, setIsGenerating] = useState(false);

  // Fetch filter options for collections
  const { data: filterOptions, isLoading: isLoadingFilters } =
    api.userVehicle.getFilterOptions.useQuery();

  // AI generation mutation
  const generateContentMutation = api.userVehicle.generateVehicleContent.useMutation();

  const form = useForm<VehicleDetailsFormData>({
    resolver: zodResolver(vehicleDetailsSchema),
    defaultValues: {
      name: "", // Will be auto-generated by backend
      description: defaultValues?.description ?? "",
      collectionIds: defaultValues?.collectionIds ?? [],
    },
  });

  // Generate AI content on mount if vehicle data is provided
  useEffect(() => {
    // Only generate if we have vehicle data and no default description
    if (vehicleData && !defaultValues?.description) {
      const generateContent = async () => {
        setIsGenerating(true);
        try {
          const generated = await generateContentMutation.mutateAsync(vehicleData);
          
          // Set the generated description (name is handled by backend)
          form.setValue("description", generated.description, { shouldValidate: true });
          
          toast.success("Vehicle description generated with AI!");
        } catch (error) {
          console.error("Failed to generate content:", error);
          toast.error("Failed to generate AI content. You can add a description manually.");
        } finally {
          setIsGenerating(false);
        }
      };

      void generateContent();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [vehicleData?.makeId, vehicleData?.modelId]); // Only run when vehicle IDs change

  // Watch form validity and notify parent
  useEffect(() => {
    const subscription = form.watch(() => {
      const isValid = form.formState.isValid;
      onValidationChange?.(isValid);
    });
    return () => subscription.unsubscribe();
  }, [form, onValidationChange]);

  // Expose submit function to parent via ref (for Next button)
  useEffect(() => {
    (window as any).__currentStepSubmit = () => {
      form.handleSubmit((data) => {
        onComplete(data);
      })();
    };
    return () => {
      delete (window as any).__currentStepSubmit;
    };
  }, [form, onComplete]);

  const watchDescription = form.watch("description");
  const descriptionLength = watchDescription?.length ?? 0;

  // Convert collections to options
  const collectionOptions: CollectionItem[] = useMemo(() => {
    const collections = filterOptions?.collections as CollectionItem[] | undefined;
    return collections ?? [];
  }, [filterOptions?.collections]);

  return (
    <div className="space-y-6">
      {/* Loading overlay */}
      {isGenerating && (
        <div className="fixed inset-0 bg-background/80 backdrop-blur-sm z-50 flex items-center justify-center">
          <div className="bg-card border rounded-lg p-8 shadow-lg max-w-md mx-4">
            <div className="flex flex-col items-center gap-4">
              <div className="relative">
                <div className="animate-spin rounded-full h-16 w-16 border-b-2 border-primary"></div>
                <Sparkles className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 h-8 w-8 text-primary" />
              </div>
              <div className="text-center">
                <h3 className="text-lg font-semibold">Generating with AI</h3>
                <p className="text-sm text-muted-foreground mt-1">
                  Creating a compelling description for your vehicle...
                </p>
              </div>
            </div>
          </div>
        </div>
      )}

      <div>
        <h2 className="text-xl md:text-2xl font-bold">Vehicle Details</h2>
        <p className="text-sm md:text-base text-muted-foreground mt-1">
          Add a description and tags to make your vehicle stand out
        </p>
      </div>

      <Form {...form}>
        <form className="space-y-6">
          {/* Description */}
          <FormField
            control={form.control}
            name="description"
            render={({ field }) => (
              <FormItem>
                <FormLabel className="text-sm md:text-base">Description</FormLabel>
                <FormControl>
                  <Textarea
                    placeholder="Tell us about your vehicle's history, features, modifications, etc."
                    className="min-h-[120px] md:min-h-[150px] resize-none text-base md:text-sm"
                    disabled={isGenerating}
                    {...field}
                    value={field.value ?? ""}
                  />
                </FormControl>
                <div className="flex justify-between items-center min-h-[20px]">
                  <FormDescription className="text-xs md:text-sm">
                    Optional but recommended for better visibility
                  </FormDescription>
                  <span className="text-xs text-muted-foreground">{descriptionLength} / 2000</span>
                </div>
                <FormMessage />
              </FormItem>
            )}
          />

          {/* Collections & Tags */}
          <FormField
            control={form.control}
            name="collectionIds"
            render={({ field }) => (
              <FormItem>
                <FormLabel className="text-sm md:text-base">Collections & Tags</FormLabel>
                <FormControl>
                  <div className="flex flex-wrap gap-2">
                    {collectionOptions.length > 0 ? (
                      collectionOptions.map((collection) => {
                        const isSelected = (field.value ?? []).includes(collection.id);
                        return (
                          <button
                            key={collection.id}
                            type="button"
                            onClick={() => {
                              const currentIds = field.value ?? [];
                              if (isSelected) {
                                // Remove if already selected
                                field.onChange(currentIds.filter((id: string) => id !== collection.id));
                              } else {
                                // Add if not selected
                                field.onChange([...currentIds, collection.id]);
                              }
                            }}
                            disabled={isLoadingFilters || isGenerating}
                            className={`
                              px-3 md:px-4 py-2 rounded-md border-2 transition-all text-sm md:text-base
                              ${isSelected 
                                ? 'border-primary bg-primary text-primary-foreground shadow-sm' 
                                : 'border-input bg-background hover:bg-accent hover:text-accent-foreground'
                              }
                            `}
                            style={
                              isSelected && collection.color
                                ? {
                                    backgroundColor: collection.color,
                                    borderColor: collection.color,
                                    color: '#ffffff',
                                  }
                                : {}
                            }
                          >
                            <div className="flex items-center gap-2">
                              {collection.color && !isSelected && (
                                <div
                                  className="w-3 h-3 rounded-full"
                                  style={{ backgroundColor: collection.color }}
                                />
                              )}
                              <span>{collection.name}</span>
                              {isSelected && (
                                <Check className="h-4 w-4" />
                              )}
                            </div>
                          </button>
                        );
                      })
                    ) : (
                      <p className="text-sm text-muted-foreground">No collections available</p>
                    )}
                  </div>
                </FormControl>
                <FormDescription className="min-h-[20px] text-xs md:text-sm">
                  Optional: Select one or more collections to categorize your vehicle
                </FormDescription>
                <FormMessage />
              </FormItem>
            )}
          />
        </form>
      </Form>
    </div>
  );
}

