"use client";

import { useEffect, useMemo } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { Check } from "lucide-react";
import {
  Form,
  FormControl,
  FormDescription,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "~/components/ui/form";
import { Input } from "~/components/ui/input";
import { Textarea } from "~/components/ui/textarea";
import { api } from "~/trpc/react";
import { vehicleDetailsSchema, type VehicleDetailsFormData, type VehicleDetailsSubmitData } from "./validation";
import type { CollectionItem } from "./types";

interface VehicleDetailsStepProps {
  onComplete: (data: VehicleDetailsSubmitData) => void;
  defaultValues?: Partial<VehicleDetailsSubmitData>;
  onValidationChange?: (isValid: boolean) => void;
  autoGeneratedName?: string; // Name generated from make, model, year
}

/**
 * Vehicle Details Step Component
 * 
 * Collects final vehicle details:
 * - Name (can use auto-generated name from make, model, year)
 * - Description (optional)
 * - Collections/Tags (optional)
 * 
 * Vehicle is created after this step is completed.
 */
export function VehicleDetailsStep({
  onComplete,
  defaultValues,
  onValidationChange,
  autoGeneratedName,
}: VehicleDetailsStepProps) {
  // Fetch filter options for collections
  const { data: filterOptions, isLoading: isLoadingFilters } =
    api.userVehicle.getFilterOptions.useQuery();

  const form = useForm<VehicleDetailsFormData>({
    resolver: zodResolver(vehicleDetailsSchema),
    defaultValues: {
      name: defaultValues?.name ?? autoGeneratedName ?? "",
      description: defaultValues?.description ?? "",
      collectionIds: defaultValues?.collectionIds ?? [],
    },
  });

  // Update name if auto-generated name changes (e.g., from previous steps)
  useEffect(() => {
    if (autoGeneratedName && !form.formState.dirtyFields.name && !defaultValues?.name) {
      form.setValue("name", autoGeneratedName);
    }
  }, [autoGeneratedName, form, defaultValues?.name]);

  // Watch form validity and notify parent
  useEffect(() => {
    const subscription = form.watch(() => {
      const isValid = form.formState.isValid;
      onValidationChange?.(isValid);
    });
    return () => subscription.unsubscribe();
  }, [form, onValidationChange]);

  // Expose submit function to parent via ref (for Next button)
  useEffect(() => {
    (window as any).__currentStepSubmit = () => {
      form.handleSubmit((data) => {
        onComplete(data);
      })();
    };
    return () => {
      delete (window as any).__currentStepSubmit;
    };
  }, [form, onComplete]);

  const watchDescription = form.watch("description");
  const descriptionLength = watchDescription?.length ?? 0;

  // Convert collections to options
  const collectionOptions: CollectionItem[] = useMemo(() => {
    const collections = filterOptions?.collections as CollectionItem[] | undefined;
    return collections ?? [];
  }, [filterOptions?.collections]);

  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-xl md:text-2xl font-bold">Vehicle Details</h2>
        <p className="text-sm md:text-base text-muted-foreground mt-1">
          Add a name, description, and tags to make your vehicle stand out
        </p>
      </div>

      <Form {...form}>
        <form className="space-y-6">
          {/* Vehicle Name */}
          <FormField
            control={form.control}
            name="name"
            render={({ field }) => (
              <FormItem>
                <FormLabel className="text-sm md:text-base">Vehicle Name *</FormLabel>
                <FormControl>
                  <Input
                    placeholder="E.g., BMW M3 2020"
                    className="h-11 md:h-10 text-base md:text-sm"
                    {...field}
                  />
                </FormControl>
                <FormDescription className="min-h-[20px] text-xs md:text-sm">
                  {autoGeneratedName 
                    ? "Pre-filled based on make, model and year. You can edit if needed."
                    : "Give your vehicle a descriptive name"}
                </FormDescription>
                <FormMessage />
              </FormItem>
            )}
          />

          {/* Description */}
          <FormField
            control={form.control}
            name="description"
            render={({ field }) => (
              <FormItem>
                <FormLabel className="text-sm md:text-base">Description</FormLabel>
                <FormControl>
                  <Textarea
                    placeholder="Tell us about your vehicle's history, features, modifications, etc."
                    className="min-h-[120px] md:min-h-[150px] resize-none text-base md:text-sm"
                    {...field}
                    value={field.value ?? ""}
                  />
                </FormControl>
                <div className="flex justify-between items-center min-h-[20px]">
                  <FormDescription className="text-xs md:text-sm">
                    Optional but recommended for better visibility
                  </FormDescription>
                  <span className="text-xs text-muted-foreground">{descriptionLength} / 2000</span>
                </div>
                <FormMessage />
              </FormItem>
            )}
          />

          {/* Collections & Tags */}
          <FormField
            control={form.control}
            name="collectionIds"
            render={({ field }) => (
              <FormItem>
                <FormLabel className="text-sm md:text-base">Collections & Tags</FormLabel>
                <FormControl>
                  <div className="flex flex-wrap gap-2">
                    {collectionOptions.length > 0 ? (
                      collectionOptions.map((collection) => {
                        const isSelected = (field.value ?? []).includes(collection.id);
                        return (
                          <button
                            key={collection.id}
                            type="button"
                            onClick={() => {
                              const currentIds = field.value ?? [];
                              if (isSelected) {
                                // Remove if already selected
                                field.onChange(currentIds.filter((id: string) => id !== collection.id));
                              } else {
                                // Add if not selected
                                field.onChange([...currentIds, collection.id]);
                              }
                            }}
                            disabled={isLoadingFilters}
                            className={`
                              px-3 md:px-4 py-2 rounded-md border-2 transition-all text-sm md:text-base
                              ${isSelected 
                                ? 'border-primary bg-primary text-primary-foreground shadow-sm' 
                                : 'border-input bg-background hover:bg-accent hover:text-accent-foreground'
                              }
                            `}
                            style={
                              isSelected && collection.color
                                ? {
                                    backgroundColor: collection.color,
                                    borderColor: collection.color,
                                    color: '#ffffff',
                                  }
                                : {}
                            }
                          >
                            <div className="flex items-center gap-2">
                              {collection.color && !isSelected && (
                                <div
                                  className="w-3 h-3 rounded-full"
                                  style={{ backgroundColor: collection.color }}
                                />
                              )}
                              <span>{collection.name}</span>
                              {isSelected && (
                                <Check className="h-4 w-4" />
                              )}
                            </div>
                          </button>
                        );
                      })
                    ) : (
                      <p className="text-sm text-muted-foreground">No collections available</p>
                    )}
                  </div>
                </FormControl>
                <FormDescription className="min-h-[20px] text-xs md:text-sm">
                  Optional: Select one or more collections to categorize your vehicle
                </FormDescription>
                <FormMessage />
              </FormItem>
            )}
          />
        </form>
      </Form>
    </div>
  );
}

