/**
 * UK Cities and Counties - Allowed values for address dropdowns
 * Source: GitHub Issue #45
 */

export const UK_CITIES = [
  "Aberdeen",
  "Armagh",
  "Bangor",
  "Bath",
  "Belfast",
  "Birmingham",
  "Bradford",
  "Brighton & Hove",
  "Bristol",
  "Cambridge",
  "Canterbury",
  "Cardiff",
  "Carlisle",
  "Chelmsford",
  "Chester",
  "Chichester",
  "Colchester",
  "Coventry",
  "Derby",
  "Doncaster",
  "Dundee",
  "Dunfermline",
  "Durham",
  "Edinburgh",
  "Ely",
  "Exeter",
  "Glasgow",
  "Gloucester",
  "Hereford",
  "Inverness",
  "Kingston-upon-Hull",
  "Lancaster",
  "Leeds",
  "Leicester",
  "Lichfield",
  "Lincoln",
  "Lisburn",
  "Liverpool",
  "London",
  "Londonderry",
  "Manchester",
  "Milton Keynes",
  "Newcastle-upon-Tyne",
  "Newport",
  "Newry",
  "Norwich",
  "Nottingham",
  "Oxford",
  "Perth",
  "Peterborough",
  "Plymouth",
  "Portsmouth",
  "Preston",
  "Ripon",
  "Salford",
  "Salisbury",
  "Sheffield",
  "Southampton",
  "Southend-on-Sea",
  "St Albans",
  "St Asaph",
  "St Davids",
  "Stirling",
  "Stoke on Trent",
  "Sunderland",
  "Swansea",
  "Truro",
  "Wakefield",
  "Wells",
  "Westminster",
  "Winchester",
  "Wolverhampton",
  "Worcester",
  "Wrexham",
  "York",
] as const;

export const UK_COUNTIES = [
  "Aberdeenshire",
  "Angus",
  "Antrim",
  "Argyll & Bute",
  "Armagh",
  "Ayrshire",
  "Banffshire",
  "Bedfordshire",
  "Berkshire",
  "Berwickshire",
  "Blaenau Gwent",
  "Bridgend",
  "Bristol",
  "Buckinghamshire",
  "Caerphilly",
  "Caithness",
  "Cambridgeshire",
  "Cardiff",
  "Carmarthenshire",
  "Ceredigion",
  "Cheshire",
  "Clackmannanshire",
  "Conwy",
  "Cornwall",
  "County Down",
  "County Durham",
  "Cumbria",
  "Denbighshire",
  "Derbyshire",
  "Devon",
  "Dorset",
  "Dumfries & Galloway",
  "East Ayrshire",
  "East Dunbartonshire",
  "East Lothian",
  "East Renfrewshire",
  "East Riding of Yorkshire",
  "East Sussex",
  "Essex",
  "Fermanagh",
  "Fife",
  "Flintshire",
  "Gloucestershire",
  "Greater London",
  "Greater Manchester",
  "Gwynedd",
  "Hampshire",
  "Herefordshire",
  "Hertfordshire",
  "Highland",
  "Inverclyde",
  "Isle of Anglesey",
  "Isle of Wight",
  "Kent",
  "Kincardineshire",
  "Lanarkshire",
  "Lancashire",
  "Leicestershire",
  "Lincolnshire",
  "Londonderry",
  "Merseyside",
  "Merthyr Tydfil",
  "Midlothian",
  "Monmouthshire",
  "Moray",
  "Neath Port Talbot",
  "Newport",
  "Norfolk",
  "North Ayrshire",
  "North Lanarkshire",
  "North Somerset",
  "North Yorkshire",
  "Northamptonshire",
  "Northumberland",
  "Nottinghamshire",
  "Orkney",
  "Oxfordshire",
  "Pembrokeshire",
  "Perth & Kinross",
  "Powys",
  "Renfrewshire",
  "Rhondda Cynon Taff",
  "Rutland",
  "Scottish Borders",
  "Shetland",
  "Shropshire",
  "Somerset",
  "South Ayrshire",
  "South Gloucestershire",
  "South Lanarkshire",
  "South Yorkshire",
  "Staffordshire",
  "Stirlingshire",
  "Suffolk",
  "Surrey",
  "Swansea",
  "Torfaen",
  "Tyne & Wear",
  "Tyrone",
  "Vale of Glamorgan",
  "Warwickshire",
  "West Dunbartonshire",
  "West Lothian",
  "West Midlands",
  "West Sussex",
  "West Yorkshire",
  "Western Isles",
  "Wiltshire",
  "Worcestershire",
  "Wrexham",
] as const;

export type UKCity = (typeof UK_CITIES)[number];
export type UKCounty = (typeof UK_COUNTIES)[number];
