/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'hero-slides': HeroSlide;
    stats: Stat;
    'value-props': ValueProp;
    'featured-vehicles-config': FeaturedVehiclesConfig;
    'cta-blocks': CtaBlock;
    testimonials: Testimonial;
    faqs: Faq;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'hero-slides': HeroSlidesSelect<false> | HeroSlidesSelect<true>;
    stats: StatsSelect<false> | StatsSelect<true>;
    'value-props': ValuePropsSelect<false> | ValuePropsSelect<true>;
    'featured-vehicles-config': FeaturedVehiclesConfigSelect<false> | FeaturedVehiclesConfigSelect<true>;
    'cta-blocks': CtaBlocksSelect<false> | CtaBlocksSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    navigation: Navigation;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Rotating hero section slides for homepage
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-slides".
 */
export interface HeroSlide {
  id: number;
  image: number | Media;
  heading: string;
  subheading?: string | null;
  ctaText?: string | null;
  ctaLink?: string | null;
  /**
   * Lower numbers appear first
   */
  order: number;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * Key metrics displayed as badges on homepage
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stats".
 */
export interface Stat {
  id: number;
  label: string;
  value: string;
  /**
   * Icon name or identifier (e.g., "car", "users", "check-circle")
   */
  icon?: string | null;
  /**
   * Lower numbers appear first
   */
  order: number;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * Feature grid highlighting platform benefits
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "value-props".
 */
export interface ValueProp {
  id: number;
  title: string;
  description: string;
  /**
   * Icon name or identifier (e.g., "shield", "star", "check-circle")
   */
  icon?: string | null;
  /**
   * Lower numbers appear first
   */
  order: number;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * Configure which vehicles appear in the featured section
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "featured-vehicles-config".
 */
export interface FeaturedVehiclesConfig {
  id: number;
  /**
   * How to select featured vehicles
   */
  selectionType: 'manual' | 'newest' | 'price-range';
  /**
   * How many vehicles to display (1-12)
   */
  count: number;
  /**
   * JSON criteria for automatic selection (e.g., {"minPrice": 10000, "maxPrice": 50000})
   */
  criteria?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Internal notes about this configuration
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Call-to-action sections with customizable placement
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cta-blocks".
 */
export interface CtaBlock {
  id: number;
  heading: string;
  description: string;
  buttonText: string;
  buttonLink: string;
  backgroundStyle: 'primary' | 'secondary' | 'accent';
  /**
   * Where this CTA block should appear
   */
  placement: 'homepage' | 'sidebar' | 'footer';
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * Customer testimonials and reviews displayed across the website
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  /**
   * The testimonial text from the customer
   */
  quote: string;
  author: string;
  /**
   * Author's role or relationship to the service
   */
  role?: string | null;
  /**
   * Rating from 1 to 5 stars
   */
  rating?: number | null;
  /**
   * Optional photo of the person giving the testimonial
   */
  image?: (number | null) | Media;
  /**
   * Category for filtering testimonials by use case
   */
  category?: ('vehicle-owner' | 'renter' | 'wedding' | 'film') | null;
  /**
   * Show this testimonial on homepage and featured sections
   */
  featured?: boolean | null;
  /**
   * Lower numbers appear first
   */
  order: number;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * Frequently asked questions displayed across the website
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  /**
   * Detailed answer with formatting, links, and lists
   */
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Category for organizing FAQs by topic
   */
  category?: ('general' | 'vehicle-owners' | 'renters' | 'pricing' | 'technical') | null;
  /**
   * Order within category - lower numbers appear first
   */
  order: number;
  /**
   * Show this FAQ on homepage and featured sections
   */
  featured?: boolean | null;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'hero-slides';
        value: number | HeroSlide;
      } | null)
    | ({
        relationTo: 'stats';
        value: number | Stat;
      } | null)
    | ({
        relationTo: 'value-props';
        value: number | ValueProp;
      } | null)
    | ({
        relationTo: 'featured-vehicles-config';
        value: number | FeaturedVehiclesConfig;
      } | null)
    | ({
        relationTo: 'cta-blocks';
        value: number | CtaBlock;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-slides_select".
 */
export interface HeroSlidesSelect<T extends boolean = true> {
  image?: T;
  heading?: T;
  subheading?: T;
  ctaText?: T;
  ctaLink?: T;
  order?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stats_select".
 */
export interface StatsSelect<T extends boolean = true> {
  label?: T;
  value?: T;
  icon?: T;
  order?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "value-props_select".
 */
export interface ValuePropsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  icon?: T;
  order?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "featured-vehicles-config_select".
 */
export interface FeaturedVehiclesConfigSelect<T extends boolean = true> {
  selectionType?: T;
  count?: T;
  criteria?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cta-blocks_select".
 */
export interface CtaBlocksSelect<T extends boolean = true> {
  heading?: T;
  description?: T;
  buttonText?: T;
  buttonLink?: T;
  backgroundStyle?: T;
  placement?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  author?: T;
  role?: T;
  rating?: T;
  image?: T;
  category?: T;
  featured?: T;
  order?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  order?: T;
  featured?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Site-wide navigation menus, footer columns, and social links
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  /**
   * Primary navigation links displayed in header
   */
  mainMenu?:
    | {
        label: string;
        link: string;
        /**
         * Optional dropdown menu items
         */
        children?:
          | {
              label: string;
              link: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Optional icon name or identifier
         */
        icon?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Footer content organized in columns (5 columns from design)
   */
  footerColumns?:
    | {
        /**
         * Optional title for the column (most columns have no title)
         */
        title?: string | null;
        /**
         * Type determines how the column is rendered
         */
        type?: ('links' | 'contact') | null;
        /**
         * For "links" type columns
         */
        links?:
          | {
              label: string;
              url: string;
              id?: string | null;
            }[]
          | null;
        /**
         * For "contact" type columns
         */
        contactInfo?: {
          addressLabel?: string | null;
          addressValue?: string | null;
          emailLabel?: string | null;
          emailValue?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Social media profiles displayed in footer
   */
  socialLinks?:
    | {
        platform: 'facebook' | 'instagram' | 'twitter' | 'linkedin';
        url: string;
        /**
         * Icon name or path (e.g., "instagram-24px")
         */
        icon?: string | null;
        id?: string | null;
      }[]
    | null;
  footerSettings?: {
    copyrightText?: string | null;
    privacyPolicyUrl?: string | null;
    termsOfServiceUrl?: string | null;
    /**
     * Display large SPOKE wordmark in footer
     */
    showLargeLogo?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Global site settings including branding, SEO defaults, and contact information
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  /**
   * Short tagline or slogan for the site
   */
  tagline?: string | null;
  /**
   * Main logo used in header and throughout the site
   */
  logo?: (number | null) | Media;
  /**
   * Browser favicon (16x16 or 32x32 px)
   */
  favicon?: (number | null) | Media;
  /**
   * Default SEO values used when pages don't specify their own
   */
  seoDefaults?: {
    defaultMetaDescription?: string | null;
    /**
     * Default image for social media sharing (1200x630 px recommended)
     */
    defaultOgImage?: (number | null) | Media;
  };
  analytics?: {
    /**
     * Google Analytics 4 measurement ID
     */
    googleAnalyticsId?: string | null;
  };
  /**
   * Copyright text displayed in footer
   */
  copyrightText?: string | null;
  /**
   * General contact details used in footer and contact pages
   */
  contactInfo?: {
    email?: string | null;
    phone?: string | null;
    address?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  mainMenu?:
    | T
    | {
        label?: T;
        link?: T;
        children?:
          | T
          | {
              label?: T;
              link?: T;
              id?: T;
            };
        icon?: T;
        id?: T;
      };
  footerColumns?:
    | T
    | {
        title?: T;
        type?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        contactInfo?:
          | T
          | {
              addressLabel?: T;
              addressValue?: T;
              emailLabel?: T;
              emailValue?: T;
            };
        id?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        icon?: T;
        id?: T;
      };
  footerSettings?:
    | T
    | {
        copyrightText?: T;
        privacyPolicyUrl?: T;
        termsOfServiceUrl?: T;
        showLargeLogo?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  logo?: T;
  favicon?: T;
  seoDefaults?:
    | T
    | {
        defaultMetaDescription?: T;
        defaultOgImage?: T;
      };
  analytics?:
    | T
    | {
        googleAnalyticsId?: T;
      };
  copyrightText?: T;
  contactInfo?:
    | T
    | {
        email?: T;
        phone?: T;
        address?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}