/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    icons: Icon;
    'hero-slides': HeroSlide;
    stats: Stat;
    'value-props': ValueProp;
    'cta-blocks': CtaBlock;
    testimonials: Testimonial;
    faqs: Faq;
    'carousel-images': CarouselImage;
    spotlights: Spotlight;
    'static-pages': StaticPage;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    icons: IconsSelect<false> | IconsSelect<true>;
    'hero-slides': HeroSlidesSelect<false> | HeroSlidesSelect<true>;
    stats: StatsSelect<false> | StatsSelect<true>;
    'value-props': ValuePropsSelect<false> | ValuePropsSelect<true>;
    'cta-blocks': CtaBlocksSelect<false> | CtaBlocksSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    'carousel-images': CarouselImagesSelect<false> | CarouselImagesSelect<true>;
    spotlights: SpotlightsSelect<false> | SpotlightsSelect<true>;
    'static-pages': StaticPagesSelect<false> | StaticPagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    navigation: Navigation;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Custom SVG icons for use across the website
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "icons".
 */
export interface Icon {
  id: number;
  /**
   * Unique identifier for the icon (e.g., "car", "shield")
   */
  name: string;
  /**
   * Upload the SVG icon file from Figma
   */
  svg: number | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * Rotating hero section slides for homepage
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-slides".
 */
export interface HeroSlide {
  id: number;
  image: number | Media;
  heading: string;
  subheading?: string | null;
  ctaText?: string | null;
  ctaLink?: string | null;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * Key metrics displayed as badges on homepage
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stats".
 */
export interface Stat {
  id: number;
  label: string;
  /**
   * Select an icon from the Icons collection
   */
  icon?: (number | null) | Icon;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * Feature grid highlighting platform benefits
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "value-props".
 */
export interface ValueProp {
  id: number;
  title: string;
  description: string;
  /**
   * Select an icon from the Icons collection
   */
  icon?: (number | null) | Icon;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * Call-to-action sections
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cta-blocks".
 */
export interface CtaBlock {
  id: number;
  heading: string;
  /**
   * Select the HTML heading level for semantic structure
   */
  headingLevel: 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6';
  description: string;
  /**
   * Add one or more action buttons (optional)
   */
  actions?:
    | {
        label: string;
        link: string;
        style: 'primary' | 'secondary' | 'outline';
        id?: string | null;
      }[]
    | null;
  backgroundStyle: 'primary' | 'secondary' | 'accent';
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * Customer testimonials and reviews displayed across the website
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  /**
   * The testimonial text from the customer
   */
  quote: string;
  author: string;
  /**
   * Author's role or relationship to the service
   */
  role?: string | null;
  /**
   * Rating from 1 to 5 stars
   */
  rating?: number | null;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * Frequently asked questions displayed across the website
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  /**
   * Detailed answer with formatting, links, and lists
   */
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * Images for image carousel blocks (supports mobile and desktop variants)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carousel-images".
 */
export interface CarouselImage {
  id: number;
  /**
   * Image displayed on desktop and tablet devices
   */
  desktopImage: number | Media;
  /**
   * Optional: Image displayed on mobile devices. Falls back to desktop image if not provided.
   */
  mobileImage?: (number | null) | Media;
  /**
   * Required for accessibility. Describe the image content.
   */
  alt: string;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * Project spotlight items for reuse across multiple pages
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "spotlights".
 */
export interface Spotlight {
  id: number;
  /**
   * Portrait orientation image (3:4 aspect ratio recommended)
   */
  image: number | Media;
  /**
   * Project title displayed below the image
   */
  caption: string;
  /**
   * Optional link to project detail page
   */
  link?: string | null;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * Create and manage static pages and articles using the page builder. Articles are accessible at /articles/[slug] and use a specialized template.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "static-pages".
 */
export interface StaticPage {
  id: number;
  title: string;
  /**
   * URL path for this page (accessible at /[slug])
   */
  slug: string;
  status: 'draft' | 'published';
  /**
   * Auto-set when status changes to published
   */
  publishedAt?: string | null;
  /**
   * Build your page by adding and arranging content blocks
   */
  layout: (
    | {
        /**
         * Optional title for the section
         */
        title?: string | null;
        displayStyle?: ('badges' | 'cards' | 'minimal' | 'large') | null;
        /**
         * Select stats to display (order matters)
         */
        selectedStats: (number | Stat)[];
        /**
         * Number of columns on desktop
         */
        columns?: ('2' | '3' | '4') | null;
        backgroundColor?: ('default' | 'muted' | 'accent' | 'primary') | null;
        /**
         * Hide this block on mobile devices (screens < 640px)
         */
        hideOnMobile?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'stats-bar';
      }
    | {
        /**
         * Select stats to display (order matters)
         */
        selectedStats: (number | Stat)[];
        backgroundColor?: ('default' | 'muted' | 'accent' | 'primary') | null;
        /**
         * Hide this block on mobile devices (screens < 640px)
         */
        hideOnMobile?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'value-stats';
      }
    | {
        title: string;
        /**
         * Supporting text below the title
         */
        subtitle?: string | null;
        selectedProps: (number | ValueProp)[];
        displayStyle?: ('grid' | 'list' | 'carousel') | null;
        columns?: ('2' | '3' | '4') | null;
        /**
         * Hide this block on mobile devices (screens < 640px)
         */
        hideOnMobile?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'value-props-section';
      }
    | {
        title?: string | null;
        selectedTestimonials: (number | Testimonial)[];
        showRatings?: boolean | null;
        /**
         * Hide this block on mobile devices (screens < 640px)
         */
        hideOnMobile?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'testimonials-section';
      }
    | {
        title?: string | null;
        /**
         * Support multiline text with formatting
         */
        subtitle?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        /**
         * Select specific FAQs to display
         */
        selectedFAQs: (number | Faq)[];
        /**
         * Expand all FAQ items by default
         */
        defaultExpanded?: boolean | null;
        /**
         * Hide this block on mobile devices (screens < 640px)
         */
        hideOnMobile?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'faq-section';
      }
    | {
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        /**
         * Hide this block on mobile devices (screens < 640px)
         */
        hideOnMobile?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'rich-text-content';
      }
    | {
        selectedCTA: number | CtaBlock;
        /**
         * Hide this block on mobile devices (screens < 640px)
         */
        hideOnMobile?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'call-to-action-block';
      }
    | {
        title?: string | null;
        subtitle?: string | null;
        selectionType?: ('manual' | 'latest') | null;
        /**
         * Enter vehicle IDs manually (one per line)
         */
        vehicleIds?:
          | {
              vehicleId: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Number of latest vehicles to display
         */
        limit?: number | null;
        /**
         * Display the 'Show all vehicles' button on mobile devices
         */
        showMobileButton?: boolean | null;
        /**
         * Hide this block on mobile devices (screens < 640px)
         */
        hideOnMobile?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'featured-vehicles';
      }
    | {
        title?: string | null;
        images: {
          image: number | Media;
          caption?: string | null;
          /**
           * Optional URL when image is clicked
           */
          link?: string | null;
          id?: string | null;
        }[];
        displayStyle?: ('grid' | 'masonry' | 'carousel' | 'lightbox-grid') | null;
        columns?: ('2' | '3' | '4' | '5') | null;
        /**
         * Hide this block on mobile devices (screens < 640px)
         */
        hideOnMobile?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'image-gallery';
      }
    | {
        /**
         * Select carousel images to display (order matters)
         */
        images: (number | CarouselImage)[];
        /**
         * Automatically advance to next image
         */
        autoplay?: boolean | null;
        /**
         * Seconds between automatic slide transitions
         */
        autoplayDelay?: number | null;
        /**
         * Hide this block on mobile devices (screens < 640px)
         */
        hideOnMobile?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'image-carousel';
      }
    | {
        leftColumn: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        rightColumn: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        columnRatio?: ('50-50' | '60-40' | '40-60' | '70-30' | '30-70') | null;
        /**
         * Stack columns in reverse order on mobile
         */
        reverseOnMobile?: boolean | null;
        verticalAlignment?: ('top' | 'center' | 'bottom') | null;
        /**
         * Hide this block on mobile devices (screens < 640px)
         */
        hideOnMobile?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'two-column-content';
      }
    | {
        /**
         * Title displayed above the spotlight items
         */
        title?: string | null;
        /**
         * Select spotlight items to display (order matters)
         */
        selectedSpotlights: (number | Spotlight)[];
        /**
         * Display left/right arrow buttons for navigation
         */
        showArrows?: boolean | null;
        /**
         * Number of items visible at once (default: 4)
         */
        itemsPerView?: number | null;
        /**
         * Hide this block on mobile devices (screens < 640px)
         */
        hideOnMobile?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'project-spotlight';
      }
    | {
        title: string;
        items: {
          /**
           * Optional custom number (e.g., "01", "02"). If empty, will auto-increment.
           */
          number?: string | null;
          heading: string;
          description: string;
          id?: string | null;
        }[];
        /**
         * Hide this block on mobile devices (screens < 640px)
         */
        hideOnMobile?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'numbered-list';
      }
    | {
        /**
         * Vertical spacing between sections
         */
        height?: ('small' | 'medium' | 'large' | 'extra-large') | null;
        /**
         * Hide this block on mobile devices (screens < 640px)
         */
        hideOnMobile?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'spacer';
      }
  )[];
  /**
   * Search engine optimization settings
   */
  seo?: {
    /**
     * Defaults to page title if not set (max 60 characters)
     */
    metaTitle?: string | null;
    /**
     * Brief description for search results (max 160 characters)
     */
    metaDescription?: string | null;
    /**
     * Title for social media sharing (defaults to Meta Title)
     */
    ogTitle?: string | null;
    /**
     * Description for social media sharing (defaults to Meta Description)
     */
    ogDescription?: string | null;
    /**
     * Image for social media sharing (1200x630 recommended)
     */
    ogImage?: (number | null) | Media;
    /**
     * Keywords for SEO (optional)
     */
    keywords?:
      | {
          keyword: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'icons';
        value: number | Icon;
      } | null)
    | ({
        relationTo: 'hero-slides';
        value: number | HeroSlide;
      } | null)
    | ({
        relationTo: 'stats';
        value: number | Stat;
      } | null)
    | ({
        relationTo: 'value-props';
        value: number | ValueProp;
      } | null)
    | ({
        relationTo: 'cta-blocks';
        value: number | CtaBlock;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'carousel-images';
        value: number | CarouselImage;
      } | null)
    | ({
        relationTo: 'spotlights';
        value: number | Spotlight;
      } | null)
    | ({
        relationTo: 'static-pages';
        value: number | StaticPage;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "icons_select".
 */
export interface IconsSelect<T extends boolean = true> {
  name?: T;
  svg?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-slides_select".
 */
export interface HeroSlidesSelect<T extends boolean = true> {
  image?: T;
  heading?: T;
  subheading?: T;
  ctaText?: T;
  ctaLink?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stats_select".
 */
export interface StatsSelect<T extends boolean = true> {
  label?: T;
  icon?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "value-props_select".
 */
export interface ValuePropsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  icon?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cta-blocks_select".
 */
export interface CtaBlocksSelect<T extends boolean = true> {
  heading?: T;
  headingLevel?: T;
  description?: T;
  actions?:
    | T
    | {
        label?: T;
        link?: T;
        style?: T;
        id?: T;
      };
  backgroundStyle?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  author?: T;
  role?: T;
  rating?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carousel-images_select".
 */
export interface CarouselImagesSelect<T extends boolean = true> {
  desktopImage?: T;
  mobileImage?: T;
  alt?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "spotlights_select".
 */
export interface SpotlightsSelect<T extends boolean = true> {
  image?: T;
  caption?: T;
  link?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "static-pages_select".
 */
export interface StaticPagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  publishedAt?: T;
  layout?:
    | T
    | {
        'stats-bar'?:
          | T
          | {
              title?: T;
              displayStyle?: T;
              selectedStats?: T;
              columns?: T;
              backgroundColor?: T;
              hideOnMobile?: T;
              id?: T;
              blockName?: T;
            };
        'value-stats'?:
          | T
          | {
              selectedStats?: T;
              backgroundColor?: T;
              hideOnMobile?: T;
              id?: T;
              blockName?: T;
            };
        'value-props-section'?:
          | T
          | {
              title?: T;
              subtitle?: T;
              selectedProps?: T;
              displayStyle?: T;
              columns?: T;
              hideOnMobile?: T;
              id?: T;
              blockName?: T;
            };
        'testimonials-section'?:
          | T
          | {
              title?: T;
              selectedTestimonials?: T;
              showRatings?: T;
              hideOnMobile?: T;
              id?: T;
              blockName?: T;
            };
        'faq-section'?:
          | T
          | {
              title?: T;
              subtitle?: T;
              selectedFAQs?: T;
              defaultExpanded?: T;
              hideOnMobile?: T;
              id?: T;
              blockName?: T;
            };
        'rich-text-content'?:
          | T
          | {
              content?: T;
              hideOnMobile?: T;
              id?: T;
              blockName?: T;
            };
        'call-to-action-block'?:
          | T
          | {
              selectedCTA?: T;
              hideOnMobile?: T;
              id?: T;
              blockName?: T;
            };
        'featured-vehicles'?:
          | T
          | {
              title?: T;
              subtitle?: T;
              selectionType?: T;
              vehicleIds?:
                | T
                | {
                    vehicleId?: T;
                    id?: T;
                  };
              limit?: T;
              showMobileButton?: T;
              hideOnMobile?: T;
              id?: T;
              blockName?: T;
            };
        'image-gallery'?:
          | T
          | {
              title?: T;
              images?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    link?: T;
                    id?: T;
                  };
              displayStyle?: T;
              columns?: T;
              hideOnMobile?: T;
              id?: T;
              blockName?: T;
            };
        'image-carousel'?:
          | T
          | {
              images?: T;
              autoplay?: T;
              autoplayDelay?: T;
              hideOnMobile?: T;
              id?: T;
              blockName?: T;
            };
        'two-column-content'?:
          | T
          | {
              leftColumn?: T;
              rightColumn?: T;
              columnRatio?: T;
              reverseOnMobile?: T;
              verticalAlignment?: T;
              hideOnMobile?: T;
              id?: T;
              blockName?: T;
            };
        'project-spotlight'?:
          | T
          | {
              title?: T;
              selectedSpotlights?: T;
              showArrows?: T;
              itemsPerView?: T;
              hideOnMobile?: T;
              id?: T;
              blockName?: T;
            };
        'numbered-list'?:
          | T
          | {
              title?: T;
              items?:
                | T
                | {
                    number?: T;
                    heading?: T;
                    description?: T;
                    id?: T;
                  };
              hideOnMobile?: T;
              id?: T;
              blockName?: T;
            };
        spacer?:
          | T
          | {
              height?: T;
              hideOnMobile?: T;
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        keywords?:
          | T
          | {
              keyword?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Site-wide navigation menus, footer columns, and social links
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  /**
   * Primary navigation links displayed in header
   */
  mainMenu?:
    | {
        label: string;
        link: string;
        /**
         * Optional dropdown menu items
         */
        children?:
          | {
              label: string;
              link: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Optional icon name or identifier
         */
        icon?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Footer content organized in columns (5 columns from design)
   */
  footerColumns?:
    | {
        /**
         * Optional title for the column (most columns have no title)
         */
        title?: string | null;
        /**
         * Type determines how the column is rendered
         */
        type?: ('links' | 'contact') | null;
        /**
         * For "links" type columns
         */
        links?:
          | {
              label: string;
              url: string;
              id?: string | null;
            }[]
          | null;
        /**
         * For "contact" type columns
         */
        contactInfo?: {
          addressLabel?: string | null;
          addressValue?: string | null;
          emailLabel?: string | null;
          emailValue?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Social media profiles displayed in footer
   */
  socialLinks?:
    | {
        platform: 'facebook' | 'instagram' | 'twitter' | 'linkedin';
        url: string;
        /**
         * Icon name or path (e.g., "instagram-24px")
         */
        icon?: string | null;
        id?: string | null;
      }[]
    | null;
  footerSettings?: {
    copyrightText?: string | null;
    privacyPolicyUrl?: string | null;
    termsOfServiceUrl?: string | null;
    /**
     * Display large SPOKE wordmark in footer
     */
    showLargeLogo?: boolean | null;
  };
  /**
   * URL slug for the home page (used for logo link and redirects)
   */
  homeSlug?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Global site settings including branding, SEO defaults, and contact information
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  /**
   * Short tagline or slogan for the site
   */
  tagline?: string | null;
  /**
   * Main logo used in header and throughout the site
   */
  logo?: (number | null) | Media;
  /**
   * Browser favicon (16x16 or 32x32 px)
   */
  favicon?: (number | null) | Media;
  /**
   * Default SEO values used when pages don't specify their own
   */
  seoDefaults?: {
    defaultMetaDescription?: string | null;
    /**
     * Default image for social media sharing (1200x630 px recommended)
     */
    defaultOgImage?: (number | null) | Media;
  };
  analytics?: {
    /**
     * Google Analytics 4 measurement ID
     */
    googleAnalyticsId?: string | null;
  };
  /**
   * Copyright text displayed in footer
   */
  copyrightText?: string | null;
  /**
   * General contact details used in footer and contact pages
   */
  contactInfo?: {
    email?: string | null;
    phone?: string | null;
    address?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  mainMenu?:
    | T
    | {
        label?: T;
        link?: T;
        children?:
          | T
          | {
              label?: T;
              link?: T;
              id?: T;
            };
        icon?: T;
        id?: T;
      };
  footerColumns?:
    | T
    | {
        title?: T;
        type?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        contactInfo?:
          | T
          | {
              addressLabel?: T;
              addressValue?: T;
              emailLabel?: T;
              emailValue?: T;
            };
        id?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        icon?: T;
        id?: T;
      };
  footerSettings?:
    | T
    | {
        copyrightText?: T;
        privacyPolicyUrl?: T;
        termsOfServiceUrl?: T;
        showLargeLogo?: T;
      };
  homeSlug?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  logo?: T;
  favicon?: T;
  seoDefaults?:
    | T
    | {
        defaultMetaDescription?: T;
        defaultOgImage?: T;
      };
  analytics?:
    | T
    | {
        googleAnalyticsId?: T;
      };
  copyrightText?: T;
  contactInfo?:
    | T
    | {
        email?: T;
        phone?: T;
        address?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}